port: 4567
debug: false
normalizeMessages: true

# Auth Config
useKeyAuth: true
key: 'change_me'
headerName: 'key'
cookieName: 'x-servertap-key'

# TLS (a.k.a. SSL) options
tls:
  # Set to true to enable TLS
  enabled: false
  # The path to your keystore (relative to ServerTap's plugin dir)
  keystore: keystore.jks
  # The password for the keystore
  keystorePassword: ""
  # Enforce Server Name Indication (SNI) or not
  sni: false

# Cores Config
# Use this list to set allowed CORS Origins ("*" by default)
corsOrigins:
  - "*"

# Webhook Config
#webhooks:
#  default:
#    listener: "https://your-webhook-target.com/whatever"
#    events:
#      - PlayerJoin
#      - PlayerQuit
#      - PlayerKick
#      - PlayerDeath
#      - PlayerChat

# Websocket Config
websocket:
  enabled: false
  clientEvents:
    - chat.broadcast
    - chat.tell
    - economy.debit
    - economy.pay
    - placeholder.replace
    - plugin.download
    - server.ping
    - server.exec
    - server.whitelist.add
    - server.whitelist.delete
    - server.world.save
    - server.worlds.save
    - server.events.subscribe
    - server.events.unsubscribe
    - executeCommand
  serverEvents:
    - player.join
    - player.quit
    - player.kicked
    - server.playerlist.online.updated
    - server.playerlist.all.updated
    - server.worlds.updated
    - server.updated
    - server.whitelist.updated
    - server.opslist.updated
  console:
    enabled: false
    buffer: 1000

#Swagger Config
# If you do not wish to show the swagger UI you can disable it here
disable-swagger: false

# Advanced Auth Config
# Use this feature to configure paths that will be blocked. Put in the exact paths shown by swagger.
blocked-paths:
# - /v1/ping
# - /v1/players/{uuid}
# - /v1/server/*
